context('Test food demand model outputs')
library(dplyr)

test_that('Food demand model runs and produces the expected result with old parameters from Edmonds et al.', {
    ps <- 0.1
    pn <- 0.5
    y <- seq(0.1, 10, 0.1)
    samp.params <- vec2param(c(1.28,1.14,-0.19,0.21,-0.33,0.5,0.1,16,5.06,100,20))
    expect_silent(rslt <- food.dmnd(ps, pn, y, samp.params))
    expect_equal_to_reference(rslt, 'food_demand_result.rds', update=FALSE)
})


test_that('New food demand budget shares are not unreasonable', {
    parameter_data <- read.csv("../../outputs/parameter_data.csv")
    params <- vec2param(c(parameter_data$params_vector.par))
    ps <- 0.1
    pn <- 0.5
    y <- seq(0.1, 10, 0.1)
    expect_silent(rslt <- food.dmnd(ps, pn, y, params))

    rslt %>% dplyr:::mutate(alpha.t = alpha.s+alpha.n) %>%
                    filter(alpha.t >0.9)->tmp

    as.numeric(nrow(tmp))->e_rows

    expect(e_rows==0,"Budget shares generated by the food demand model are higher than 90 percent at some income levels.")
})



