write.fddata <- function(dlist, stem='food-dmnd-price', byname=FALSE)
{
    ## dlist:  list of data subsets (e.g., as generated by split(...))
    ## stem:  filename stem
    ## byname:  TRUE - name files using names(dlist).
    ##          FALSE - name files using sequential numbers.
    if(byname) {
        ## Get names of groupings.  Replace whitespace and underscores with hyphens.
        itervals <- gsub('[[:space:]_]+', '-', names(dlist))
    }
    else {
        itervals <- seq_along(names(dlist))
    }

    for(iter in itervals) {
        ## construct filename
        fn <- paste(stem,'.',iter,'.dat', sep='')
        write.csv(dlist[[iter]], file = fn, row.names=FALSE)
    }
}
